spring.application.name=auramoon

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HoS;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none


# VNPay Configuration Sandbox
vnp_PayUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp_ReturnUrl=/billing/checkout/vnpay-return
vnp_TmnCode=${vnp_TmnCode_Secret}
vnp_HashSecret=${vnp_HashSecret_Secret}

spring.config.import=optional:classpath:application-secret.properties


# ===================================================================
# EMAIL SMTP CONFIGURATION (Fill in your credentials)
# ===================================================================
 spring.mail.host=smtp.gmail.com
 spring.mail.port=587
 spring.mail.username=auramoonretreat@gmail.com
 spring.mail.password=gact npzi jpwb pyhs
spring.mail.properties.mail.smtp.auth=true
 spring.mail.properties.mail.smtp.starttls.enable=true

# ===================================================================
# GOOGLE OAUTH2 SSO CONFIGURATION (Fill in your credentials)
# ===================================================================
 spring.security.oauth2.client.registration.google.client-id=336555754067-dclu2gm1ultv06ihen91gu8j1d0lsue0.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
 spring.security.oauth2.client.registration.google.scope=profile,email
 spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

# Encryption Key for PII (CCCD/Passport) AES-256
app.encryption.key=${ENCRYPTION_KEY:AuraMoonRetreatWellnessSystem206}
